(in-package #:asdf-user)

(defsystem "cl-weave"
  :description "A modern Common Lisp testing framework inspired by Vitest."
  :author "takeokunn <bararararatty@gmail.com>"
  :maintainer "takeokunn <bararararatty@gmail.com>"
  :license "MIT"
  :version "1.3.0"
  :homepage "https://github.com/nerima-lisp/cl-weave"
  :bug-tracker "https://github.com/nerima-lisp/cl-weave/issues"
  :source-control (:git "https://github.com/nerima-lisp/cl-weave.git")
  :build-operation "program-op"
  :build-pathname "../cl-weave"
  :entry-point "cl-weave/cli::image-entry-point"
  :depends-on (#+sbcl (:require "sb-cover"))
  :pathname "src"
  :serial t
  :components
  ((:file "package")
   (:file "platform-protocol")
   (:file "platform-portable")
   (:file "platform-sbcl")
   (:file "model")
   (:file "model-registry")
   (:file "model-registration")
   (:file "journal")
   (:file "replay")
   (:file "soft")
   (:file "benchmark")
   (:file "logic")
   (:file "logic-queries")
   (:file "isolation")
   (:file "snapshots-storage")
   (:file "snapshots-session")
   (:file "snapshots")
   (:file "mocks-data")
   (:file "mocks")
   (:file "mocks-lifecycle")
   (:file "matcher-core")
   (:file "matcher-structural")
   (:file "matcher-runtime")
   (:file "matcher-builtins")
   (:file "expectation")
   (:file "property-core")
   (:file "property-generators-equality")
   (:file "property-generators-shrinking")
   (:file "property-generators-primitives")
   (:file "property-generators")
   (:file "property-runner")
   (:file "mutation-model")
   (:file "mutation-operators")
   (:file "mutation-walker")
   (:file "mutation-runner")
   (:file "registration")
   (:file "registration-tests")
   (:file "fixtures")
   (:file "continuations")
   (:file "expect-runtime")
   (:file "expect")
   (:file "reporter-schema")
   (:file "reporter-schema-data")
   (:file "reporter-json")
   (:file "reporter-results")
   (:file "reporter-tap")
   (:file "reporter-github")
   (:file "reporter-plan")
   (:file "reporter-mutation")
   (:file "reporter-junit")
   (:file "runner-control-data")
   (:file "runner-control")
   (:file "runner-hooks")
   (:file "runner-attempts")
   (:file "runner-selection")
   (:file "runner-planning")
   (:file "runner-concurrency")
   (:file "runner-collection")
   (:file "runner-collection-plan")
   (:file "runner-coverage")
   (:file "runner-api")
   (:file "watch-discovery")
   (:file "watch-scope")
   (:file "watch-suite-diff")
   (:file "watch-registry-compaction")
   (:file "watch-reload")
   (:file "watch")
   (:file "cli-options")
   (:file "cli-options-parsers")
   (:file "cli-options-data")
   (:file "cli-metadata-project-data")
   (:file "cli-metadata-quality-data")
   (:file "cli-metadata-option-data")
   (:file "cli-metadata-capability-data")
   (:file "cli-metadata-core")
   (:file "cli-metadata-doctor")
   (:file "cli-metadata-json-core")
   (:file "cli-metadata-json-schema")
   (:file "cli-metadata-json-schema-data")
   (:file "cli-metadata-reporting")
   (:file "cli")
   (:file "cli-execution")
   (:file "cli-image"))
  :in-order-to ((test-op (test-op "cl-weave/test"))))
(defsystem "cl-weave/test"
  :description "Self tests for cl-weave."
  :author "takeokunn <bararararatty@gmail.com>"
  :maintainer "takeokunn <bararararatty@gmail.com>"
  :license "MIT"
  :version "1.3.0"
  :homepage "https://github.com/nerima-lisp/cl-weave"
  :bug-tracker "https://github.com/nerima-lisp/cl-weave/issues"
  :source-control (:git "https://github.com/nerima-lisp/cl-weave.git")
  :depends-on ("cl-weave")
  :pathname "t"
  :serial t
  :components
  ((:file "package")
   (:file "helpers-support")
   (:file "expect-core-test")
   (:file "snapshots-runtime-test")
   (:file "expect-failures-test")
   (:file "matcher-core-extensions-test")
   (:file "matcher-core-records-test")
   (:file "registration-macros-test")
   (:file "isolation-test")
   (:file "helpers-property")
   (:file "property-generators-test")
   (:file "property-generators-shrinking-test")
   (:file "property-runner-shrinking-test")
   (:file "property-runner-environment-test")
   (:file "registration-fuzz-test")
   (:file "mutation-runner-test")
   (:file "fixtures-test")
   (:file "continuations-test")
   (:file "platform-protocol-timeout-test")
   (:file "runner-collection-tag-filter-test")
   (:file "runner-api-preflight-test")
   (:file "runner-attempts-test")
   (:file "runner-concurrency-test")
   (:file "runner-coverage-preflight-test")
   (:file "runner-coverage-test")
   (:file "registration-expected-failures-test")
   (:file "registration-skips-test")
   (:file "registration-todos-test")
   (:file "runner-selection-focus-test")
   (:file "runner-selection-filtering-test")
   (:file "runner-selection-sharding-test")
   (:file "runner-selection-sequence-test")
   (:file "runner-api-list-mode-test")
   (:file "logic-test")
   (:file "runner-control-bail-test")
   (:file "helpers-workflow")
   (:file "cli-options-test")
   (:file "cli-execution-test")

   (:file "cli-metadata-doctor-test")
   (:file "cli-metadata-project-data-links-test")
   (:file "cli-metadata-reporting-artifact-test")
   (:file "cli-metadata-quality-data-test")
   (:file "cli-metadata-capability-data-test")
   (:file "cli-metadata-project-data-contracts-test")
   (:file "cli-execution-entrypoint-test")
   (:file "cli-image-test")
   (:file "watch-asdf-integration-test")
   (:file "watch-discovery-test")
   (:file "watch-scope-test")
   (:file "watch-suite-diff-test")
   (:file "watch-run-test")
   (:file "watch-state-refresh-test")
   (:file "benchmark-test")
   (:file "mocks-test")
   (:file "mocks-spy-lifecycle-test")
   (:file "reporter-results-test")
   (:file "reporter-plan-test")
   (:file "reporter-schema-test")
   (:file "reporter-ci-test")
   (:file "runner-api-status-test")
   (:file "runner-control-runtime-test")
   (:file "journal-test")
   (:file "replay-test")
   (:file "soft-test")
   (:file "runner-api-test"))
  :perform (test-op (op c)
             (declare (ignore op c))
             (unless (uiop:symbol-call :cl-weave :run-all :reporter :spec :pass-with-no-tests nil)
               (error "cl-weave self test suite failed."))))
