(in-package #:cl-weave)

(defun registry-reachable-objects-unlocked (root)
  (let ((registrations (make-hash-table :test #'eq))
        (suites (make-hash-table :test #'eq))
        (stack (when root (list root))))
    (flet ((record-list (values)
             (dolist (value values)
               (setf (gethash value registrations) t))))
      (loop while stack
            for suite = (pop stack)
            unless (gethash suite suites)
              do (setf (gethash suite registrations) t
                       (gethash suite suites) t)
                 (record-list (suite-before-all suite))
                 (record-list (suite-after-all suite))
                 (record-list (suite-before-each suite))
                 (record-list (suite-around-each suite))
                 (record-list (suite-after-each suite))
                 (dolist (child (suite-children suite))
                   (setf (gethash child registrations) t)
                   (when (suite-p child)
                     (push child stack)))))
    (values registrations suites)))

(define-locked-registry-operation registry-reachable-objects
    (root)
  registry-reachable-objects-unlocked)

(defun compact-registration-owner-table-unlocked (root)
  (multiple-value-bind (reachable suites)
      (registry-reachable-objects-unlocked root)
    (declare (ignore suites))
    (let ((compacted (make-hash-table :test #'eq)))
      (maphash
       (lambda (registration pathname)
         (when (gethash registration reachable)
           (setf (gethash registration compacted) pathname)))
       *registration-owners*)
      compacted)))

(defun compact-named-suite-table-unlocked (root)
  (multiple-value-bind (registrations reachable-suites)
      (registry-reachable-objects-unlocked root)
    (declare (ignore registrations))
    (let ((compacted (make-hash-table :test #'equal)))
      (maphash
       (lambda (key suite)
         (when (gethash suite reachable-suites)
           (setf (gethash key compacted) suite)))
       *named-suites*)
      compacted)))
